<section class="sg-colors" data-mage-init='{"ba.styleguideColors:{}}"'>
    <h3 class="sg-h">Colors</h3>
    <ul class="ba-grid">
        {{#colors}}
            <li class="item span-s-6 span-m-4 span-l-2 brand-{{style}}">
                <span></span>
                <p>
                    <span>{{name}}</span>
                    <span>{{less}}</span>
                    <span>{{color}}</span>
                </p>
            </li>
        {{/colors}}
    </ul>
</section>