<?php
/**
 * @package     BlueAcorn/CmsFramework
 * @author      Blue Acorn iCi <code@blueacorn.com>
 * @copyright   Copyright © Blue Acorn iCi. All Rights Reserved.
 */

// @codingStandardsIgnoreFile
// phpcs:disable Generic.Files.LineLength.TooLong

/**
 * CMS Framework Documentation Template
 *
 * @var $block \BlueAcorn\CmsFramework\Block\CmsFramework
 */
?>

<div class="ba-grid margin-bottom-40 padding-left-0 padding-right-0">
    <h3 class="item span-12">Sprites</h3>

    {{#shapes}}
    <h4 class="item span-12">{{name}}</h4>

    <div class="item span-s-12 d-flex flex-wrap margin-bottom-5">
        <div class="padding-10 float-left d-flex justify-content-center align-content-center bg-white c-contrast-white">
            <i class="svg-icon-{{name}}"><span class="visually-hidden">{{name}}</span></i>
        </div>
        <div class="padding-10 float-left d-flex justify-content-center align-content-center bg-black c-contrast-black">
            <i class="svg-icon-{{name}}"><span class="visually-hidden">{{name}}</span></i>
        </div>
        <dl class="padding-10 float-left bg-white c-contrast-white">
            <dt>Width</dt>
            <dd>{{width.outer}}</dd>
            <dt>Height</dt>
            <dd>{{height.outer}}</dd>
            <dt>Background Position Mixin</dt>
            <dd>.svg-{{name}}()</dd>
            <dt>Dimensions Mixin</dt>
            <dd>.svg-{{name}}-dims()</dd>
            <dt>Full Mixin</dt>
            <dd>.svgi-{{name}}()</dd>
            <dt>Class</dt>
            <dd>.svg-icon-{{name}}()</dd>
        </dl>
    </div>

    <pre class="item span-s-12 margin-bottom-20"><code>&lt;i class="svg-icon-{{name}}"&gt;&lt;span class="visually-hidden"&gt;{{name}}&lt;/span&gt;&lt;/i&gt;</code></pre>
    {{/shapes}}
</div>
