<?php
/**
 * @package     BlueAcorn/site
 * @author      Blue Acorn iCi <code@blueacorn.com>
 * @copyright   Copyright © Blue Acorn iCi. All rights reserved.
 */

// phpcs:disable Generic.Files.LineLength.TooLong

?>
<section class="sg-svg-sprites">
    <h3 class="sg-h">SVG Sprites</h3>
    <div class="ba-grid">
        {{#shapes}}
        <div class="item span-3">
            <i class="svg-icon-{{name}}"><span class="visually-hidden">.svg-icon-{{name}}</span></i>
            <span class="icon-name">.svg-icon-{{name}}</span>
        </div>
        {{/shapes}}
    </div>
</section>
